apiVersion: 1

datasources:
  - name: Elasticsearch eCommerce
    type: elasticsearch
    uid: es-ecommerce
    url: http://es-latest:9200
    access: proxy
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: changeme
    jsonData:
      index: kibana_sample_data_ecommerce
      timeField: order_date
      esVersion: "8.0.0"
      logMessageField: ""
      logLevelField: ""
      maxConcurrentShardRequests: 5
    version: 1
    editable: true
    isDefault: true
